[platformio]
default_envs = jc_esp32p4_m3

[env:jc_esp32p4_m3]
platform = https://github.com/platformio/platform-espressif32.git
board = jc_esp32p4_m3
framework = espidf
monitor_speed = 115200
upload_speed = 921600

; Change LED GPIO if your board routes the on-board LED differently.
build_flags =
  -D LED_GPIO=2
